# -*- coding: utf-8 -*-
"""Basics of Programming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-UVcITcBuMEjam5IMwYPKlYY9cPahhp
"""

import numpy as np


def Rhombus_check(a):
  z=a
  d1=np.sqrt(pow((z[0][0]-z[2][0]),2)+pow((z[0][1]-z[2][1]),2))
  d2=np.sqrt(pow((z[1][0]-z[3][0]),2)+pow((z[1][1]-z[3][1]),2))
  sd1=((z[2][1]-z[0][1]))/((z[2][0]-z[0][0]))
  sd2=((z[3][1]-z[1][1]))/((z[3][0]-z[1][0]))
  if (sd1*sd2==-1)and (d1==d2):
    return "Given figure is Rhombus"
Rhombus_check(np.array([[1,1],[1,-1],[-1,-1],[-1,1]]))